import type { Chain } from 'types/chains'

// source https://github.com/cosmos/composer/blob/master/react/src/types/settings.ts
// fixme: some networks data not correct, osmosis for example
export const CHAIN_LIST: Chain[] = [
  {
    rpc: `http://cosmos-test-2.adoriasoft.link:26657`,
    rest: `http://cosmos-test-2.adoriasoft.link:1317`,
    id: 'cosmoswithgroups',
    name: 'GROUPS-UI-TEST',
    coinDenom: 'STAKE',
    coinMinimalDenom: 'stake',
  },
  {
    rpc: `http://${window.location.hostname}:26657`,
    rest: `http://${window.location.hostname}:1317`,
    id: 'cosmoswithgroups',
    name: 'GROUPS-UI-TEST-LOCAL',
    coinDenom: 'STAKE',
    coinMinimalDenom: 'stake',
  },
  {
    rpc: 'https://rpc-juno.itastakers.com',
    rest: 'https://lcd-juno.itastakers.com',
    id: 'juno-1',
    name: 'Juno',
    coinDenom: 'juno',
    coinMinimalDenom: 'ujuno',
  },
  {
    rpc: 'https://rpc-cosmoshub.keplr.app',
    rest: 'https://lcd-cosmoshub.keplr.app',
    id: 'cosmoshub-4',
    name: 'Cosmos',
    coinDenom: 'atom',
    coinMinimalDenom: 'uatom',
  },
  {
    rpc: 'https://vega-rpc.interchain.io',
    rest: 'https://vega-rest.interchain.io',
    id: 'vega-testnet',
    name: 'vega-testnet',
    coinDenom: 'atom',
    coinMinimalDenom: 'uatom',
  },
  {
    rpc: 'https://rpc-osmosis.blockapsis.com',
    rest: 'https://lcd-osmosis.blockapsis.com',
    id: 'osmosis-1',
    name: 'Osmosis',
    coinDenom: 'osmo',
    coinMinimalDenom: 'uosmo',
  },
  {
    rpc: 'https://rpc-secret.keplr.app',
    rest: 'https://lcd-secret.keplr.app',
    id: 'secret-3',
    name: 'Secret Network',
    coinDenom: 'scrt',
    coinMinimalDenom: 'uscrt',
  },
  {
    rpc: 'https://rpc-akash.keplr.app',
    rest: 'https://lcd-akash.keplr.app',
    id: 'akashnet-2',
    name: 'Akash',
    coinDenom: 'akash',
    coinMinimalDenom: 'uakash',
  },
  {
    rpc: 'https://rpc-crypto-org.keplr.app',
    rest: 'https://lcd-crypto-org.keplr.app',
    id: 'crypto-org-chain-mainnet-1',
    name: 'Crypto.org',
    coinDenom: 'cro',
    coinMinimalDenom: 'ucro',
  },
  {
    rpc: 'https://rpc-iov.keplr.app',
    rest: 'https://lcd-iov.keplr.app',
    id: 'iov-mainnet-ibc',
    name: 'Starname',
    coinDenom: 'aiov',
    coinMinimalDenom: 'uiov',
  },
  {
    rpc: 'https://rpc-sifchain.keplr.app',
    rest: 'https://lcd-sifchain.keplr.app/',
    id: 'sifchain-1',
    name: 'Sifchain',
    coinDenom: 'rowan',
    coinMinimalDenom: 'urowan',
  },
  {
    rpc: 'https://rpc-certik.keplr.app',
    rest: 'https://lcd-certik.keplr.app',
    id: 'shentu-2.2',
    name: 'Certik',
    coinDenom: 'ctk',
    coinMinimalDenom: 'uctk',
  },
  {
    rpc: 'https://rpc-iris.keplr.app',
    rest: 'https://lcd-iris.keplr.app',
    id: 'irishub-1',
    name: 'IRISnet',
    coinDenom: 'iris',
    coinMinimalDenom: 'uiris',
  },
  {
    rpc: 'https://rpc-regen.keplr.app',
    rest: 'https://lcd-regen.keplr.app',
    id: 'regen-1',
    name: 'Regen',
    coinDenom: 'regen',
    coinMinimalDenom: 'uregen',
  },
  {
    rpc: 'https://rpc-persistence.keplr.app',
    rest: 'https://lcd-persistence.keplr.app',
    id: 'core-1',
    name: 'Persistence',
    coinDenom: 'xrpt',
    coinMinimalDenom: 'uxrpt',
  },
  {
    rpc: 'https://rpc-sentinel.keplr.app',
    rest: 'https://lcd-sentinel.keplr.app',
    id: 'sentinelhub-2',
    name: 'Sentinel',
    coinDenom: 'dvpn',
    coinMinimalDenom: 'udvpn',
  },
  {
    rpc: 'https://rpc-impacthub.keplr.app',
    rest: 'https://lcd-impacthub.keplr.app',
    id: 'impacthub-3',
    name: 'ixo',
    coinDenom: 'ixo',
    coinMinimalDenom: 'uixo',
  },
  {
    rpc: 'https://rpc-emoney.keplr.app',
    rest: 'https://lcd-emoney.keplr.app',
    id: 'emoney-3',
    name: 'e-Money',
    coinDenom: 'ngm',
    coinMinimalDenom: 'ungm',
  },
]
